# Generated by Django 5.2.5 on 2025-12-28 04:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeficiente_experticidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('indice_experticidad', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('cargo_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('grado_cientifico', models.CharField(choices=[('Doctor', 'Doctor'), ('Master', 'Máster'), ('Licenciado', 'Licenciado'), ('Técnico', 'Técnico Superior')], max_length=20)),
                ('anos_experiencia', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa_cliente', models.CharField(max_length=255)),
                ('estado_tormenta', models.CharField(choices=[('activa', 'Tormenta de Ideas Activa'), ('cerrada', 'Tormenta de Ideas Cerrada')], default='activa', max_length=10, verbose_name='Estado de la tormenta de ideas')),
                ('fecha_cierre_tormenta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre de tormenta')),
                ('investigador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_liderados', to='app.experto')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('experto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='app.experto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to='app.proyecto')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='ItemTormentaIdeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('puntuacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Evaluación'), ('seleccionado', 'Seleccionado para Desarrollo'), ('rechazado', 'Rechazado'), ('archivado', 'Archivado')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
                ('experto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_generados', to='app.experto')),
                ('experto_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_propuestos', to='app.experto', verbose_name='Experto que propuso el item')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_ideados', to='app.proyecto')),
            ],
            options={
                'verbose_name': 'Item de Tormenta de Ideas',
                'verbose_name_plural': 'Items de Tormenta de Ideas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ListaChequeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('seleccionado', 'Seleccionado para el Proyecto'), ('rechazado', 'No Seleccionado')], default='pendiente', max_length=15)),
                ('es_moderador', models.BooleanField(default=False, verbose_name='¿Es moderador del proyecto?')),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('coeficiente_experticidad_en_decision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selecciones_expertos', to=settings.AUTH_USER_MODEL)),
                ('experto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones_proyectos', to='app.experto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_chequeo_expertos', to='app.proyecto')),
            ],
            options={
                'verbose_name': 'Lista de Chequeo de Experto',
                'verbose_name_plural': 'Listas de Chequeo de Expertos',
                'ordering': ['proyecto', '-coeficiente_experticidad_en_decision'],
                'unique_together': {('proyecto', 'experto')},
            },
        ),
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Completar'), ('completada', 'Completada por Experto'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada')], default='pendiente', max_length=15)),
                ('cargo_actual', models.CharField(max_length=255)),
                ('anos_experiencia', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Años de experiencia en el cargo')),
                ('grado_cientifico', models.CharField(max_length=20)),
                ('conocimiento_materia', models.IntegerField(blank=True, help_text='Valor del 0 al 10 sobre el grado de conocimientos en la materia', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('influencia_analisis_teoricos', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=1, verbose_name='Análisis teóricos realizados por usted')),
                ('influencia_experiencia', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=1, verbose_name='Su experiencia obtenida')),
                ('influencia_autores_nacionales', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=1, verbose_name='Trabajos de autores nacionales')),
                ('influencia_autores_extranjeros', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=1, verbose_name='Trabajos de autores extranjeros')),
                ('influencia_conocimiento_extranjero', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=1, verbose_name='Su propio conocimiento del estado del problema en el extranjero')),
                ('influencia_intuicion', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=1, verbose_name='Su intuición')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('coeficiente_k', models.DecimalField(blank=True, decimal_places=2, help_text='Coeficiente de experticidad calculado', max_digits=5, null=True)),
                ('experto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_experticidad', to='app.experto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_experticidad', to='app.proyecto')),
            ],
            options={
                'verbose_name': 'Encuesta de Experticidad',
                'verbose_name_plural': 'Encuestas de Experticidad',
                'unique_together': {('proyecto', 'experto')},
            },
        ),
        migrations.CreateModel(
            name='VotoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_acuerdo', models.BooleanField(default=False, verbose_name='¿Está de acuerdo con este item?')),
                ('evaluacion', models.IntegerField(blank=True, choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy Alto')], null=True, verbose_name='Nivel de Evaluación')),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('experto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_items', to='app.experto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos', to='app.itemtormentaideas')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones_items', to='app.proyecto')),
            ],
            options={
                'verbose_name': 'Voto de Item',
                'verbose_name_plural': 'Votos de Items',
                'ordering': ['-fecha_voto'],
                'unique_together': {('experto', 'item')},
            },
        ),
    ]
